-- CreateTable
CREATE TABLE `adocoes` (
    `ADO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ADO_DATA` DATE NOT NULL,
    `ADO_ANI_ID` INTEGER NOT NULL,
    `ADO_USR_ID` INTEGER NOT NULL,

    INDEX `fk_ADOCOES_USUARIOS1_idx`(`ADO_USR_ID`),
    INDEX `fk_DOACOES_ANIMAIS_idx`(`ADO_ANI_ID`),
    PRIMARY KEY (`ADO_ID`, `ADO_ANI_ID`, `ADO_USR_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `animais` (
    `ANI_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ANI_NOME` VARCHAR(180) NOT NULL,
    `ANI_DESCRICAO` VARCHAR(400) NOT NULL,
    `ANI_ESPECIE` VARCHAR(80) NOT NULL,
    `ANI_GENERO` TINYINT NOT NULL,
    `ANI_USR_ID` INTEGER NOT NULL,
    `ANI_RAC_ID` INTEGER NOT NULL,

    UNIQUE INDEX `animais_ANI_ID_key`(`ANI_ID`),
    INDEX `fk_ANIMAIS_RACAS1_idx`(`ANI_RAC_ID`),
    INDEX `fk_ANIMAIS_USUARIOS1_idx`(`ANI_USR_ID`),
    PRIMARY KEY (`ANI_ID`, `ANI_USR_ID`, `ANI_RAC_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `enderecos` (
    `END_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `END_LOGRADOURO` VARCHAR(90) NOT NULL,
    `END_CIDADE` VARCHAR(120) NOT NULL,
    `END_ESTADO` VARCHAR(2) NOT NULL,
    `END_USR_ID` INTEGER NOT NULL,

    INDEX `fk_ENDERECOS_USUARIOS1_idx`(`END_USR_ID`),
    PRIMARY KEY (`END_ID`, `END_USR_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `racas` (
    `RAC_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `RAC_NOME` VARCHAR(200) NOT NULL,

    PRIMARY KEY (`RAC_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `usuarios` (
    `USR_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USR_NOME` VARCHAR(180) NOT NULL,
    `USR_EMAIL` VARCHAR(255) NOT NULL,
    `USR_TELEFONE` VARCHAR(11) NOT NULL,
    `USR_SENHA` VARCHAR(90) NOT NULL,

    UNIQUE INDEX `USR_EMAIL_UNIQUE`(`USR_EMAIL`),
    UNIQUE INDEX `USR_TELEFONE_UNIQUE`(`USR_TELEFONE`),
    PRIMARY KEY (`USR_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `adocoes` ADD CONSTRAINT `fk_ADOCOES_USUARIOS1` FOREIGN KEY (`ADO_USR_ID`) REFERENCES `usuarios`(`USR_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `adocoes` ADD CONSTRAINT `fk_DOACOES_ANIMAIS` FOREIGN KEY (`ADO_ANI_ID`) REFERENCES `animais`(`ANI_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `animais` ADD CONSTRAINT `fk_ANIMAIS_RACAS1` FOREIGN KEY (`ANI_RAC_ID`) REFERENCES `racas`(`RAC_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `animais` ADD CONSTRAINT `fk_ANIMAIS_USUARIOS1` FOREIGN KEY (`ANI_USR_ID`) REFERENCES `usuarios`(`USR_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `enderecos` ADD CONSTRAINT `fk_ENDERECOS_USUARIOS1` FOREIGN KEY (`END_USR_ID`) REFERENCES `usuarios`(`USR_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
