SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CADU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CADU` DEFAULT CHARACTER SET utf8 ;
USE `CADU` ;

-- -----------------------------------------------------
-- Table `CADU`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CADU`.`USUARIOS` (
  `USR_ID` INT NOT NULL AUTO_INCREMENT,
  `USR_NOME` VARCHAR(180) NOT NULL,
  `USR_ENDERECO` VARCHAR(400) NOT NULL,
  `USR_EMAIL` VARCHAR(255) NOT NULL,
  `USR_TELEFONE` VARCHAR(11) NOT NULL,
  `USR_SENHA` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`USR_ID`),
  UNIQUE INDEX `USR_EMAIL_UNIQUE` (`USR_EMAIL` ASC),
  UNIQUE INDEX `USR_TELEFONE_UNIQUE` (`USR_TELEFONE` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `CADU`.`RACAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CADU`.`RACAS` (
  `RAC_ID` INT NOT NULL AUTO_INCREMENT,
  `RAC_NOME` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`RAC_ID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `CADU`.`ANIMAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CADU`.`ANIMAIS` (
  `ANI_ID` INT NOT NULL AUTO_INCREMENT,
  `ANI_NOME` VARCHAR(180) NOT NULL,
  `ANI_DESCRICAO` VARCHAR(400) NOT NULL,
  `ANI_ESPECIE` VARCHAR(80) NOT NULL,
  `ANI_GENERO` TINYINT NOT NULL,
  `ANI_USR_ID` INT NOT NULL,
  `ANI_RAC_ID` INT NOT NULL,
  PRIMARY KEY (`ANI_ID`, `ANI_USR_ID`, `ANI_RAC_ID`),
  INDEX `fk_ANIMAIS_USUARIOS1_idx` (`ANI_USR_ID` ASC),
  INDEX `fk_ANIMAIS_RACAS1_idx` (`ANI_RAC_ID` ASC),
  CONSTRAINT `fk_ANIMAIS_USUARIOS1`
    FOREIGN KEY (`ANI_USR_ID`)
    REFERENCES `CADU`.`USUARIOS` (`USR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ANIMAIS_RACAS1`
    FOREIGN KEY (`ANI_RAC_ID`)
    REFERENCES `CADU`.`RACAS` (`RAC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `CADU`.`ADOCOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CADU`.`ADOCOES` (
  `ADO_ID` INT NOT NULL AUTO_INCREMENT,
  `ADO_DATA` DATE NOT NULL,
  `ADO_ANI_ID` INT NOT NULL,
  `ADO_USR_ID` INT NOT NULL,
  PRIMARY KEY (`ADO_ID`, `ADO_ANI_ID`, `ADO_USR_ID`),
  INDEX `fk_DOACOES_ANIMAIS_idx` (`ADO_ANI_ID` ASC),
  INDEX `fk_ADOCOES_USUARIOS1_idx` (`ADO_USR_ID` ASC),
  CONSTRAINT `fk_DOACOES_ANIMAIS`
    FOREIGN KEY (`ADO_ANI_ID`)
    REFERENCES `CADU`.`ANIMAIS` (`ANI_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADOCOES_USUARIOS1`
    FOREIGN KEY (`ADO_USR_ID`)
    REFERENCES `CADU`.`USUARIOS` (`USR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `CADU`.`ENDERECOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CADU`.`ENDERECOS` (
  `END_ID` INT NOT NULL AUTO_INCREMENT,
  `END_LOGRADOURO` VARCHAR(90) NOT NULL,
  `END_CIDADE` VARCHAR(120) NOT NULL,
  `END_ESTADO` VARCHAR(2) NOT NULL,
  `END_USR_ID` INT NOT NULL,
  PRIMARY KEY (`END_ID`, `END_USR_ID`),
  INDEX `fk_ENDERECOS_USUARIOS1_idx` (`END_USR_ID` ASC),
  CONSTRAINT `fk_ENDERECOS_USUARIOS1`
    FOREIGN KEY (`END_USR_ID`)
    REFERENCES `CADU`.`USUARIOS` (`USR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
